/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIdSurveyRouteImport } from './routes/sessions.$id.survey'
import { Route as SessionsIdResultsRouteImport } from './routes/sessions.$id.results'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdSurveyRoute = SessionsIdSurveyRouteImport.update({
  id: '/sessions/$id/survey',
  path: '/sessions/$id/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdResultsRoute = SessionsIdResultsRouteImport.update({
  id: '/sessions/$id/results',
  path: '/sessions/$id/results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sessions/$id/results': typeof SessionsIdResultsRoute
  '/sessions/$id/survey': typeof SessionsIdSurveyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sessions/$id/results': typeof SessionsIdResultsRoute
  '/sessions/$id/survey': typeof SessionsIdSurveyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sessions/$id/results': typeof SessionsIdResultsRoute
  '/sessions/$id/survey': typeof SessionsIdSurveyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/sessions/$id/results'
    | '/sessions/$id/survey'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/sessions/$id/results' | '/sessions/$id/survey'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/sessions/$id/results'
    | '/sessions/$id/survey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  SessionsIdResultsRoute: typeof SessionsIdResultsRoute
  SessionsIdSurveyRoute: typeof SessionsIdSurveyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id/survey': {
      id: '/sessions/$id/survey'
      path: '/sessions/$id/survey'
      fullPath: '/sessions/$id/survey'
      preLoaderRoute: typeof SessionsIdSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id/results': {
      id: '/sessions/$id/results'
      path: '/sessions/$id/results'
      fullPath: '/sessions/$id/results'
      preLoaderRoute: typeof SessionsIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SessionsIdResultsRoute: SessionsIdResultsRoute,
  SessionsIdSurveyRoute: SessionsIdSurveyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
